"""A generic, single-database configuration."""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = "0d12367ce15f"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cash_adjustments',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('request_id', sa.String(), nullable=True),
    sa.Column('happened_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('day', sa.Date(), nullable=True),
    sa.Column('delta_cash', sa.Integer(), nullable=False),
    sa.Column('note', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('reversed_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_reversed', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('request_id')
    )
    op.create_index(op.f('ix_cash_adjustments_day'), 'cash_adjustments', ['day'], unique=False)
    op.create_index(op.f('ix_cash_adjustments_happened_at'), 'cash_adjustments', ['happened_at'], unique=False)
    op.create_index(op.f('ix_cash_adjustments_id'), 'cash_adjustments', ['id'], unique=False)
    op.create_index(op.f('ix_cash_adjustments_is_reversed'), 'cash_adjustments', ['is_reversed'], unique=False)
    op.create_index(op.f('ix_cash_adjustments_reversed_id'), 'cash_adjustments', ['reversed_id'], unique=False)
    op.create_table('company_transactions',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('request_id', sa.String(), nullable=True),
    sa.Column('happened_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('day', sa.Date(), nullable=True),
    sa.Column('kind', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('buy12', sa.Integer(), nullable=False),
    sa.Column('return12', sa.Integer(), nullable=False),
    sa.Column('buy48', sa.Integer(), nullable=False),
    sa.Column('return48', sa.Integer(), nullable=False),
    sa.Column('new12', sa.Integer(), nullable=False),
    sa.Column('new48', sa.Integer(), nullable=False),
    sa.Column('total', sa.Integer(), nullable=False),
    sa.Column('paid', sa.Integer(), nullable=False),
    sa.Column('note', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('reversed_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_reversed', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('request_id')
    )
    op.create_index(op.f('ix_company_transactions_day'), 'company_transactions', ['day'], unique=False)
    op.create_index(op.f('ix_company_transactions_happened_at'), 'company_transactions', ['happened_at'], unique=False)
    op.create_index(op.f('ix_company_transactions_id'), 'company_transactions', ['id'], unique=False)
    op.create_index(op.f('ix_company_transactions_is_reversed'), 'company_transactions', ['is_reversed'], unique=False)
    op.create_index(op.f('ix_company_transactions_kind'), 'company_transactions', ['kind'], unique=False)
    op.create_index(op.f('ix_company_transactions_reversed_id'), 'company_transactions', ['reversed_id'], unique=False)
    op.create_table('customers',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('address', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('note', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customers_id'), 'customers', ['id'], unique=False)
    op.create_table('expense_categories',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_expense_categories_id'), 'expense_categories', ['id'], unique=False)
    op.create_index(op.f('ix_expense_categories_is_active'), 'expense_categories', ['is_active'], unique=False)
    op.create_table('inventory_adjustments',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('request_id', sa.String(), nullable=True),
    sa.Column('happened_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('day', sa.Date(), nullable=True),
    sa.Column('gas_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('delta_full', sa.Integer(), nullable=False),
    sa.Column('delta_empty', sa.Integer(), nullable=False),
    sa.Column('note', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('reversed_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_reversed', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('request_id')
    )
    op.create_index(op.f('ix_inventory_adjustments_day'), 'inventory_adjustments', ['day'], unique=False)
    op.create_index(op.f('ix_inventory_adjustments_gas_type'), 'inventory_adjustments', ['gas_type'], unique=False)
    op.create_index(op.f('ix_inventory_adjustments_happened_at'), 'inventory_adjustments', ['happened_at'], unique=False)
    op.create_index(op.f('ix_inventory_adjustments_id'), 'inventory_adjustments', ['id'], unique=False)
    op.create_index(op.f('ix_inventory_adjustments_is_reversed'), 'inventory_adjustments', ['is_reversed'], unique=False)
    op.create_index(op.f('ix_inventory_adjustments_reversed_id'), 'inventory_adjustments', ['reversed_id'], unique=False)
    op.create_table('price_catalog',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('effective_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('gas_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('sell_price', sa.Integer(), nullable=False),
    sa.Column('buy_price', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_price_catalog_effective_from'), 'price_catalog', ['effective_from'], unique=False)
    op.create_index(op.f('ix_price_catalog_gas_type'), 'price_catalog', ['gas_type'], unique=False)
    op.create_index(op.f('ix_price_catalog_id'), 'price_catalog', ['id'], unique=False)
    op.create_table('system_settings',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_setup_completed', sa.Boolean(), nullable=False),
    sa.Column('currency_code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('money_decimals', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('system_type_options',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_system_type_options_id'), 'system_type_options', ['id'], unique=False)
    op.create_index(op.f('ix_system_type_options_is_active'), 'system_type_options', ['is_active'], unique=False)
    op.create_table('expenses',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('request_id', sa.String(), nullable=True),
    sa.Column('happened_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('day', sa.Date(), nullable=True),
    sa.Column('kind', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('category_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('paid_from', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('note', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('vendor', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('reversed_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_reversed', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['expense_categories.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('request_id')
    )
    op.create_index(op.f('ix_expenses_day'), 'expenses', ['day'], unique=False)
    op.create_index(op.f('ix_expenses_happened_at'), 'expenses', ['happened_at'], unique=False)
    op.create_index(op.f('ix_expenses_id'), 'expenses', ['id'], unique=False)
    op.create_index(op.f('ix_expenses_is_reversed'), 'expenses', ['is_reversed'], unique=False)
    op.create_index(op.f('ix_expenses_kind'), 'expenses', ['kind'], unique=False)
    op.create_index(op.f('ix_expenses_reversed_id'), 'expenses', ['reversed_id'], unique=False)
    op.create_table('ledger_entries',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('happened_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('day', sa.Date(), nullable=True),
    sa.Column('source_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('customer_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('account', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('gas_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('state', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('unit', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('note', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_type', 'source_id', 'account', 'gas_type', 'state', 'unit', name='uq_ledger_source_account')
    )
    op.create_index(op.f('ix_ledger_entries_account'), 'ledger_entries', ['account'], unique=False)
    op.create_index(op.f('ix_ledger_entries_customer_id'), 'ledger_entries', ['customer_id'], unique=False)
    op.create_index(op.f('ix_ledger_entries_day'), 'ledger_entries', ['day'], unique=False)
    op.create_index(op.f('ix_ledger_entries_gas_type'), 'ledger_entries', ['gas_type'], unique=False)
    op.create_index(op.f('ix_ledger_entries_happened_at'), 'ledger_entries', ['happened_at'], unique=False)
    op.create_index(op.f('ix_ledger_entries_id'), 'ledger_entries', ['id'], unique=False)
    op.create_index(op.f('ix_ledger_entries_source_id'), 'ledger_entries', ['source_id'], unique=False)
    op.create_index(op.f('ix_ledger_entries_source_type'), 'ledger_entries', ['source_type'], unique=False)
    op.create_index(op.f('ix_ledger_entries_state'), 'ledger_entries', ['state'], unique=False)
    op.create_index(op.f('ix_ledger_entries_unit'), 'ledger_entries', ['unit'], unique=False)
    op.create_table('systems',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('customer_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('gas_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('note', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('requires_security_check', sa.Boolean(), nullable=False),
    sa.Column('security_check_exists', sa.Boolean(), nullable=False),
    sa.Column('last_security_check_at', sa.Date(), nullable=True),
    sa.Column('next_security_check_at', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_systems_customer_id'), 'systems', ['customer_id'], unique=False)
    op.create_index(op.f('ix_systems_gas_type'), 'systems', ['gas_type'], unique=False)
    op.create_index(op.f('ix_systems_id'), 'systems', ['id'], unique=False)
    op.create_index(op.f('ix_systems_is_active'), 'systems', ['is_active'], unique=False)
    op.create_index(op.f('ix_systems_next_security_check_at'), 'systems', ['next_security_check_at'], unique=False)
    op.create_index(op.f('ix_systems_requires_security_check'), 'systems', ['requires_security_check'], unique=False)
    op.create_index(op.f('ix_systems_security_check_exists'), 'systems', ['security_check_exists'], unique=False)
    op.create_table('customer_transactions',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('group_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('request_id', sa.String(), nullable=True),
    sa.Column('happened_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('day', sa.Date(), nullable=True),
    sa.Column('kind', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('mode', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('customer_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('system_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('gas_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('installed', sa.Integer(), nullable=False),
    sa.Column('received', sa.Integer(), nullable=False),
    sa.Column('total', sa.Integer(), nullable=False),
    sa.Column('paid', sa.Integer(), nullable=False),
    sa.Column('note', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('reversed_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_reversed', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['system_id'], ['systems.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('request_id')
    )
    op.create_index(op.f('ix_customer_transactions_customer_id'), 'customer_transactions', ['customer_id'], unique=False)
    op.create_index(op.f('ix_customer_transactions_day'), 'customer_transactions', ['day'], unique=False)
    op.create_index(op.f('ix_customer_transactions_gas_type'), 'customer_transactions', ['gas_type'], unique=False)
    op.create_index(op.f('ix_customer_transactions_group_id'), 'customer_transactions', ['group_id'], unique=False)
    op.create_index(op.f('ix_customer_transactions_happened_at'), 'customer_transactions', ['happened_at'], unique=False)
    op.create_index(op.f('ix_customer_transactions_id'), 'customer_transactions', ['id'], unique=False)
    op.create_index(op.f('ix_customer_transactions_is_reversed'), 'customer_transactions', ['is_reversed'], unique=False)
    op.create_index(op.f('ix_customer_transactions_kind'), 'customer_transactions', ['kind'], unique=False)
    op.create_index(op.f('ix_customer_transactions_mode'), 'customer_transactions', ['mode'], unique=False)
    op.create_index(op.f('ix_customer_transactions_reversed_id'), 'customer_transactions', ['reversed_id'], unique=False)
    op.create_index(op.f('ix_customer_transactions_system_id'), 'customer_transactions', ['system_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_customer_transactions_system_id'), table_name='customer_transactions')
    op.drop_index(op.f('ix_customer_transactions_reversed_id'), table_name='customer_transactions')
    op.drop_index(op.f('ix_customer_transactions_mode'), table_name='customer_transactions')
    op.drop_index(op.f('ix_customer_transactions_kind'), table_name='customer_transactions')
    op.drop_index(op.f('ix_customer_transactions_is_reversed'), table_name='customer_transactions')
    op.drop_index(op.f('ix_customer_transactions_id'), table_name='customer_transactions')
    op.drop_index(op.f('ix_customer_transactions_happened_at'), table_name='customer_transactions')
    op.drop_index(op.f('ix_customer_transactions_group_id'), table_name='customer_transactions')
    op.drop_index(op.f('ix_customer_transactions_gas_type'), table_name='customer_transactions')
    op.drop_index(op.f('ix_customer_transactions_day'), table_name='customer_transactions')
    op.drop_index(op.f('ix_customer_transactions_customer_id'), table_name='customer_transactions')
    op.drop_table('customer_transactions')
    op.drop_index(op.f('ix_systems_security_check_exists'), table_name='systems')
    op.drop_index(op.f('ix_systems_requires_security_check'), table_name='systems')
    op.drop_index(op.f('ix_systems_next_security_check_at'), table_name='systems')
    op.drop_index(op.f('ix_systems_is_active'), table_name='systems')
    op.drop_index(op.f('ix_systems_id'), table_name='systems')
    op.drop_index(op.f('ix_systems_gas_type'), table_name='systems')
    op.drop_index(op.f('ix_systems_customer_id'), table_name='systems')
    op.drop_table('systems')
    op.drop_index(op.f('ix_ledger_entries_unit'), table_name='ledger_entries')
    op.drop_index(op.f('ix_ledger_entries_state'), table_name='ledger_entries')
    op.drop_index(op.f('ix_ledger_entries_source_type'), table_name='ledger_entries')
    op.drop_index(op.f('ix_ledger_entries_source_id'), table_name='ledger_entries')
    op.drop_index(op.f('ix_ledger_entries_id'), table_name='ledger_entries')
    op.drop_index(op.f('ix_ledger_entries_happened_at'), table_name='ledger_entries')
    op.drop_index(op.f('ix_ledger_entries_gas_type'), table_name='ledger_entries')
    op.drop_index(op.f('ix_ledger_entries_day'), table_name='ledger_entries')
    op.drop_index(op.f('ix_ledger_entries_customer_id'), table_name='ledger_entries')
    op.drop_index(op.f('ix_ledger_entries_account'), table_name='ledger_entries')
    op.drop_table('ledger_entries')
    op.drop_index(op.f('ix_expenses_reversed_id'), table_name='expenses')
    op.drop_index(op.f('ix_expenses_kind'), table_name='expenses')
    op.drop_index(op.f('ix_expenses_is_reversed'), table_name='expenses')
    op.drop_index(op.f('ix_expenses_id'), table_name='expenses')
    op.drop_index(op.f('ix_expenses_happened_at'), table_name='expenses')
    op.drop_index(op.f('ix_expenses_day'), table_name='expenses')
    op.drop_table('expenses')
    op.drop_index(op.f('ix_system_type_options_is_active'), table_name='system_type_options')
    op.drop_index(op.f('ix_system_type_options_id'), table_name='system_type_options')
    op.drop_table('system_type_options')
    op.drop_table('system_settings')
    op.drop_index(op.f('ix_price_catalog_id'), table_name='price_catalog')
    op.drop_index(op.f('ix_price_catalog_gas_type'), table_name='price_catalog')
    op.drop_index(op.f('ix_price_catalog_effective_from'), table_name='price_catalog')
    op.drop_table('price_catalog')
    op.drop_index(op.f('ix_inventory_adjustments_reversed_id'), table_name='inventory_adjustments')
    op.drop_index(op.f('ix_inventory_adjustments_is_reversed'), table_name='inventory_adjustments')
    op.drop_index(op.f('ix_inventory_adjustments_id'), table_name='inventory_adjustments')
    op.drop_index(op.f('ix_inventory_adjustments_happened_at'), table_name='inventory_adjustments')
    op.drop_index(op.f('ix_inventory_adjustments_gas_type'), table_name='inventory_adjustments')
    op.drop_index(op.f('ix_inventory_adjustments_day'), table_name='inventory_adjustments')
    op.drop_table('inventory_adjustments')
    op.drop_index(op.f('ix_expense_categories_is_active'), table_name='expense_categories')
    op.drop_index(op.f('ix_expense_categories_id'), table_name='expense_categories')
    op.drop_table('expense_categories')
    op.drop_index(op.f('ix_customers_id'), table_name='customers')
    op.drop_table('customers')
    op.drop_index(op.f('ix_company_transactions_reversed_id'), table_name='company_transactions')
    op.drop_index(op.f('ix_company_transactions_kind'), table_name='company_transactions')
    op.drop_index(op.f('ix_company_transactions_is_reversed'), table_name='company_transactions')
    op.drop_index(op.f('ix_company_transactions_id'), table_name='company_transactions')
    op.drop_index(op.f('ix_company_transactions_happened_at'), table_name='company_transactions')
    op.drop_index(op.f('ix_company_transactions_day'), table_name='company_transactions')
    op.drop_table('company_transactions')
    op.drop_index(op.f('ix_cash_adjustments_reversed_id'), table_name='cash_adjustments')
    op.drop_index(op.f('ix_cash_adjustments_is_reversed'), table_name='cash_adjustments')
    op.drop_index(op.f('ix_cash_adjustments_id'), table_name='cash_adjustments')
    op.drop_index(op.f('ix_cash_adjustments_happened_at'), table_name='cash_adjustments')
    op.drop_index(op.f('ix_cash_adjustments_day'), table_name='cash_adjustments')
    op.drop_table('cash_adjustments')
    # ### end Alembic commands ###
