import { DailyReportV2Event } from "@/types/domain";

const baseEvent = {
  cash_before: 1000,
  cash_after: 1000,
};

export const level3Fixtures: DailyReportV2Event[] = [
  {
    ...baseEvent,
    event_type: "order",
    effective_at: "2026-02-14T09:00:00Z",
    created_at: "2026-02-14T09:00:00Z",
    source_id: "evt-replace-settled",
    label: "Replace",
    label_short: "Replace",
    order_mode: "replacement",
    gas_type: "12kg",
    order_installed: 1,
    order_received: 1,
    hero: { text: "Replace 12kg" },
    money: { verb: "received", amount: 150 },
    hero_primary: "Installed 1x12kg",
    money_delta: 150,
    context_line: "Replace ? 09:00 ? System: Kitchen",
    status: "atomic_ok",
    counterparty: {
      type: "customer",
      display_name: "Alpha Cafe",
      description: "Main Branch",
      display: "Alpha Cafe — Main Branch",
    },
    system: { display_name: "Kitchen" },
    status_mode: "atomic",
    is_ok: true,
    settlement: { scope: "customer", is_settled: true, components: { money: true, cyl12: true, cyl48: true } },
    action_pills: [],
  },
  {
    ...baseEvent,
    event_type: "order",
    effective_at: "2026-02-14T09:30:00Z",
    created_at: "2026-02-14T09:30:00Z",
    source_id: "evt-replace-unsettled",
    label: "Replace",
    label_short: "Replace",
    order_mode: "replacement",
    gas_type: "12kg",
    order_installed: 2,
    order_received: 1,
    hero: { text: "Replace 12kg" },
    money: { verb: "received", amount: 50 },
    hero_primary: "Installed 2x12kg",
    money_delta: 50,
    context_line: "Replace ? 09:30 ? System: Kitchen",
    status: "needs_action",
    notes: [
      {
        kind: "money",
        direction: "customer_pays_you",
        remaining_after: 100,
        remaining_before: 150,
      },
    ],
    counterparty: {
      type: "customer",
      display_name: "Alpha Cafe",
      description: "Main Branch",
      display: "Alpha Cafe — Main Branch",
    },
    system: { display_name: "Kitchen" },
    status_mode: "atomic",
    is_ok: false,
    settlement: { scope: "customer", is_settled: false, components: { money: false, cyl12: false, cyl48: true } },
    action_pills: [
      {
        category: "money",
        direction: "customer->dist",
        kind: "money",
        severity: "warning",
        text: "Customer pays ₪100",
        amount: 100,
      },
      {
        category: "cylinders",
        direction: "customer->dist",
        kind: "empty_12",
        severity: "warning",
        text: "Customer returns 2×12kg empties",
        gas_type: "12",
        qty: 2,
        unit: "empty",
      },
    ],
  },
  {
    ...baseEvent,
    event_type: "order",
    effective_at: "2026-02-14T10:00:00Z",
    created_at: "2026-02-14T10:00:00Z",
    source_id: "evt-replace-owe-full",
    label: "Replace",
    label_short: "Replace",
    order_mode: "replacement",
    gas_type: "12kg",
    order_installed: 1,
    order_received: 2,
    hero: { text: "Replace 12kg" },
    money: { verb: "none", amount: 0 },
    hero_primary: "Installed 1x12kg",
    money_delta: 0,
    context_line: "Replace ? 10:00 ? System: Stove",
    status: "needs_action",
    notes: [
      {
        kind: "cyl_full_12",
        direction: "you_deliver_customer",
        remaining_after: 1,
      },
    ],
    counterparty: {
      type: "customer",
      display_name: "Beta Market",
      description: "Downtown",
      display: "Beta Market — Downtown",
    },
    system: { display_name: "Stove" },
    status_mode: "atomic",
    is_ok: false,
    settlement: { scope: "customer", is_settled: false, components: { money: true, cyl12: false, cyl48: true } },
    action_pills: [
      {
        category: "cylinders",
        direction: "dist->customer",
        kind: "full_12",
        severity: "warning",
        text: "Deliver 1×12kg full to customer",
        gas_type: "12",
        qty: 1,
        unit: "full",
      },
    ],
  },
  {
    ...baseEvent,
    event_type: "order",
    effective_at: "2026-02-14T10:30:00Z",
    created_at: "2026-02-14T10:30:00Z",
    source_id: "evt-sell-full",
    label: "Sell Full",
    label_short: "Sell Full",
    order_mode: "sell_iron",
    gas_type: "48kg",
    order_installed: 2,
    order_received: 0,
    hero: { text: "Sell Full 48kg" },
    money: { verb: "received", amount: 300 },
    counterparty: {
      type: "customer",
      display_name: "Gamma Grill",
      description: "Terrace",
      display: "Gamma Grill — Terrace",
    },
    system: null,
    status_mode: "atomic",
    is_ok: true,
    settlement: { scope: "customer", is_settled: true, components: { money: true, cyl12: true, cyl48: true } },
    action_pills: [],
  },
  {
    ...baseEvent,
    event_type: "order",
    effective_at: "2026-02-14T11:00:00Z",
    created_at: "2026-02-14T11:00:00Z",
    source_id: "evt-buy-empty",
    label: "Buy Empty",
    label_short: "Buy Empty",
    order_mode: "buy_iron",
    gas_type: "12kg",
    order_installed: 0,
    order_received: 4,
    hero: { text: "Buy Empty 12kg" },
    money: { verb: "paid", amount: 80 },
    counterparty: {
      type: "customer",
      display_name: "Delta Hotel",
      description: "Lobby",
      display: "Delta Hotel — Lobby",
    },
    system: null,
    status_mode: "atomic",
    is_ok: false,
    settlement: { scope: "customer", is_settled: false, components: { money: false, cyl12: true, cyl48: true } },
    action_pills: [
      {
        category: "money",
        direction: "dist->customer",
        kind: "money",
        severity: "warning",
        text: "Pay customer ₪40",
        amount: 40,
      },
    ],
  },
  {
    ...baseEvent,
    event_type: "collection_money",
    effective_at: "2026-02-14T12:00:00Z",
    created_at: "2026-02-14T12:00:00Z",
    source_id: "evt-late-pay",
    label: "Late Pay",
    label_short: "Late Pay",
    hero: { text: "Late Pay" },
    money: { verb: "received", amount: 120 },
    counterparty: {
      type: "customer",
      display_name: "Alpha Cafe",
      description: "Main Branch",
      display: "Alpha Cafe — Main Branch",
    },
    system: null,
    status_mode: "settlement",
    is_ok: false,
    settlement: { scope: "customer", is_settled: false, components: { money: true, cyl12: false, cyl48: true } },
    action_pills: [
      {
        category: "cylinders",
        direction: "customer->dist",
        kind: "empty_12",
        severity: "warning",
        text: "Customer returns 1×12kg empty",
        gas_type: "12",
        qty: 1,
        unit: "empty",
      },
    ],
  },
  {
    ...baseEvent,
    event_type: "collection_empty",
    effective_at: "2026-02-14T12:30:00Z",
    created_at: "2026-02-14T12:30:00Z",
    source_id: "evt-late-return",
    label: "Return Emp",
    label_short: "Return Emp",
    return12: 3,
    return48: 1,
    hero: { text: "Late Return" },
    money: { verb: "none", amount: 0 },
    counterparty: {
      type: "customer",
      display_name: "Beta Market",
      description: "Downtown",
      display: "Beta Market — Downtown",
    },
    system: null,
    status_mode: "settlement",
    is_ok: true,
    settlement: { scope: "customer", is_settled: true, components: { money: true, cyl12: true, cyl48: true } },
    action_pills: [],
  },
  {
    ...baseEvent,
    event_type: "refill",
    effective_at: "2026-02-14T13:00:00Z",
    created_at: "2026-02-14T13:00:00Z",
    source_id: "evt-refill",
    label: "Refill",
    label_short: "Refill",
    buy12: 8,
    buy48: 2,
    hero: { text: "Refill" },
    money: { verb: "paid", amount: 300 },
    counterparty: { type: "company", display_name: "Company", description: null, display: "Company" },
    system: null,
    status_mode: "atomic",
    is_ok: false,
    settlement: { scope: "company", is_settled: false, components: { money: false, cyl12: false, cyl48: true } },
    action_pills: [
      {
        category: "money",
        direction: "dist->company",
        kind: "money",
        severity: "danger",
        text: "Pay company ₪120",
        amount: 120,
      },
      {
        category: "cylinders",
        direction: "dist->company",
        kind: "empty_12",
        severity: "danger",
        text: "Return 3×12kg empties to company",
        gas_type: "12",
        qty: 3,
        unit: "empty",
      },
    ],
  },
  {
    ...baseEvent,
    event_type: "company_payment",
    effective_at: "2026-02-14T14:00:00Z",
    created_at: "2026-02-14T14:00:00Z",
    source_id: "evt-company-payment",
    label: "Pay Company",
    label_short: "Pay Company",
    hero: { text: "Pay Company" },
    money: { verb: "paid", amount: 200 },
    counterparty: { type: "company", display_name: "Company", description: null, display: "Company" },
    system: null,
    status_mode: "settlement",
    is_ok: true,
    settlement: { scope: "company", is_settled: true, components: { money: true, cyl12: true, cyl48: true } },
    action_pills: [],
  },
  {
    ...baseEvent,
    event_type: "expense",
    effective_at: "2026-02-14T15:00:00Z",
    created_at: "2026-02-14T15:00:00Z",
    source_id: "evt-expense",
    label: "Expense",
    label_short: "Expense",
    hero: { text: "Expense: Fuel" },
    money: { verb: "paid", amount: 75 },
    counterparty: { type: "none", display_name: null, description: null, display: null },
    system: null,
    status_mode: "atomic",
    is_ok: true,
    settlement: { scope: "none", is_settled: true, components: null },
    action_pills: [],
  },
  {
    ...baseEvent,
    event_type: "adjust",
    effective_at: "2026-02-14T15:30:00Z",
    created_at: "2026-02-14T15:30:00Z",
    source_id: "evt-adjust",
    label: "Inventory Adjust",
    label_short: "Inventory Adjust",
    hero: { text: "Inventory Adjust" },
    money: { verb: "none", amount: 0 },
    counterparty: { type: "none", display_name: null, description: null, display: null },
    system: null,
    status_mode: "atomic",
    is_ok: true,
    settlement: { scope: "none", is_settled: true, components: null },
    action_pills: [],
  },
];
