export const CUSTOMER_WORDING = {
  cylinders: "Cylinders",
  money: "Money",
  installed: "Installed",
  received: "Received",
  total: "Total",
  paid: "Paid",
  returned: "Returned",
  returnedWithOld: "Returned all",
  didntReturn: "Didn't return",
  paid_: "Paid",
  paidWithDebt: "Paid all",
  didntPay: "Didn't pay",
  returnAll: "Return all",
  payAll: "Pay all",
  notes: "Note (optional)",
  cylinderDebt: (n: number, gas: string) => `Owes ${n} ${gas} cylinder${n !== 1 ? "s" : ""}`,
  cylinderCredit: (n: number, gas: string) => `${n} ${gas} cylinder${n !== 1 ? "s" : ""} credit`,
  cylinderSettled: "Settled",
  moneyDebt: (n: string) => `Owes ${n}`,
  moneyCredit: (n: string) => `${n} credit`,
  moneySettled: "Settled",
} as const;
